server:
  port: 9001
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.study.demo.dubbo.consumer.controller

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scm_transaction?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
